### PR TITLE
Add explicit download instructions before example

### PR DESCRIPTION
**Pull request by lalmeras**
From a newcomer point of view, I think more explicit instructions for tool installation may be needed. I agree that it is slightly redundant with introduction, but I think a step-by-step approach from installation to examples is a big help for a first-time usage.

### CODE REVIEW

**Review by a-langer — COMMENTED** [review]
Good suggestion, but there are two points:
1. For Windows must be ZIP format:
   ```bash
   mvn dependency:copy -Dartifact=com.github.a-langer:org.eclipse.oomph.console.product:1.0.1:zip:win32.win32.x86_64 -DoutputDirectory=.
   ```
2. The "tar" archiver may not be available on some platforms, so it might be better to extract the archive via maven. It will also be more convenient to specify the "LATEST" version in the instructions:
   ```bash
   # Linux
   mvn dependency:unpack -Dartifact=com.github.a-langer:org.eclipse.oomph.console.product:LATEST:tar.gz:linux.gtk.x86_64 -DoutputDirectory=./ -Dproject.basedir=./
   # MacOS x86_64
   mvn dependency:unpack -Dartifact=com.github.a-langer:org.eclipse.oomph.console.product:LATEST:tar.gz:macosx.cocoa.x86_64 -DoutputDirectory=./ -Dproject.basedir=./
   # Windows
   mvn dependency:unpack -Dartifact=com.github.a-langer:org.eclipse.oomph.console.product:LATEST:zip:win32.win32.x86_64 -DoutputDirectory=./ -Dproject.basedir=./
    ```

**Comment by a-langer** [comment]
To correctly unpack tar archives containing paths longer than 100 characters (see https://stackoverflow.com/a/44707967), need to specify a new version of the "dependency" plugin:

```bash
# Linux
mvn org.apache.maven.plugins:maven-dependency-plugin:3.3.0:unpack -Dartifact=com.github.a-langer:org.eclipse.oomph.console.product:LATEST:tar.gz:linux.gtk.x86_64 -DoutputDirectory=./ -Dproject.basedir=./
# MacOS x86_64
mvn org.apache.maven.plugins:maven-dependency-plugin:3.3.0:unpack -Dartifact=com.github.a-langer:org.eclipse.oomph.console.product:LATEST:tar.gz:macosx.cocoa.x86_64 -DoutputDirectory=./ -Dproject.basedir=./
# Windows
mvn org.apache.maven.plugins:maven-dependency-plugin:3.3.0:unpack -Dartifact=com.github.a-langer:org.eclipse.oomph.console.product:LATEST:zip:win32.win32.x86_64 -DoutputDirectory=./ -Dproject.basedir=./
 ```

**Comment by lalmeras** [comment]
Sorry for this incorrect PR. The last commit adds all of your suggestions.

This time, I test with Windows (I only test Linux the first time). I fix the argument escaping for powershell, and add a comment to state that Windows command is `eclipse-instc.exe`.

**Comment by a-langer** [comment]
PR approved and merged.

**Pull request merged**
